### ISSUE TITLE
Test that promise throws/rejects

### ISSUE THREAD

**Issue by whitelizard** [jprichardson/tape-promise#11]
I can't figure out how I should test that a function that returns a promise (async function) rejects/throws.

I feel I have tried everything up my sleeve: async-await vs then-catch, t.throws(), catch inside test and t.ok()/t.end(), transpiling with babel vs babel-node, etc.

How?

**Comment by zenflow** [comment]
Try something like:

```
let error
try {
  await promiseThatRejects
} catch (_error) {
  error = _error
}
t.ok(error)
```

A bit verbose but it should work

**Comment by zenflow** [comment]
It would be nice to have `t.rejects(asyncFn, expected, message)` and `t.doesNotReject(asyncFn, expected, message)`... They would be the first assertion methods added by this package

**Comment by whitelizard** [comment]
It does not work. The error always gets thrown outside the test. It seems impossible to get the test to catch the error. I don't know why your example does not work, because I agree that it should.

**Comment by zenflow** [comment]
If that's true then it seems like a bug. You could reproduce in a jsfiddle/codepen/whatever to prove it.

**Comment by whitelizard** [comment]
Sorry, this was actually a bug in the code that was tested
