### ISSUE TITLE
unexpected exceptions stop tests hard

### ISSUE THREAD

**Issue by michaelfig** [jprichardson/tape-promise#19]
I noticed with `tape-promise` (and `tape` in general) that I need to use the following pattern:

```js
test('first', async t => {
  try {
    // assertions here
  } catch (e) {
    t.assert(false, e);
  } finally {
    t.end();
  } 
});

test('second', ...);
```

or else `second` doesn't run if there's an unexpected thrown exception in the `assertions` section.

Do you have an explanation of why this is, and what the best way to work around this is?

Thanks,
Michael.

**Comment by RyanZim** [comment]
This is the way tape works, as to why it works that way, I don't know. This would be a question for the folks at tape.
