### ISSUE TITLE
fix memory leak on process.once

### ISSUE THREAD

**Issue by jprichardson** [jprichardson/tape-promise#5]
Here: https://github.com/jprichardson/tape-promise/blob/0e7df721473720e2da11e040311d5d7e260fe643/index.babel.js#L7

**Comment by jprichardson** [comment]
If there is never an `unhandledRejection`, the callback just hangs around. Really just a minor annoyance since it's a test process.

**Comment by lijunle** [comment]
Hi, @jprichardson Thanks for your cool tape wrapper. I get into [this warning](https://ci.appveyor.com/project/lijunle/appveyor-runner/build/46#L660) too. Is this a real memory leak, or a false positive? Do you have any update on this?
