### ISSUE TITLE
Incorrect signature

### ISSUE THREAD

**Issue by prashaantt** [jprichardson/tape-promise#9]
The full `tape` [signature](https://github.com/substack/tape#testname-opts-cb) looks like `test([name], [opts], cb)`. Was it an oversight to not use `opts` in `tape-promise`?

**Comment by jprichardson** [comment]
> Was it an oversight to not use opts in tape-promise?

It wasn't an oversight, it was just an implementation detail. i.e. I just wanted a solution ASAP, not necessarily a correct one. Happy to accept a PR.

**Comment by prashaantt** [comment]
My needs have since changed. I'll try submitting a PR if I get back to this lib in the future.
